### ISSUE TITLE
process-run.py is not running 

### ISSUE THREAD

**Issue by Anios2001** [remzi-arpacidusseau/ostep-projects#13]
I opened this file in idle and tried to run it but it shows a syntax error.
![python error](https://user-images.githubusercontent.com/64782002/82077891-cbe69500-96fd-11ea-8d12-e5a826f17709.png)

**Comment by KhaledEmaraDev** [comment]
You are trying to run it with Python 3.8.
This is script is written in Python 2.
You can install both concurrently.

**Comment by remzi-arpacidusseau** [comment]
This is not an issue with "ostep-projects" but rather homeworks. We will be updating homeworks to work with Python2/3 soon, but in the meanwhile, use Python2. Thank you -
Remzi
