### ISSUE TITLE
I got some problem when installing the xv6 on my Mac

### ISSUE THREAD

**Issue by PKUFlyingPig** [remzi-arpacidusseau/ostep-projects#17]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/60659728/86004611-25a0e580-ba46-11ea-8abd-86e1a3567e6e.png">
I tried to install xv6 on my Mac follow the install notes, after all the work, when I run "make TOOLPREFIX=i386-elf- qemu-nox" in the xv6-public, it began to show the above again and again. Is there  some problem? and after I install Qemu but before the second software to be installed, when I run"qemu-system-x86_64 -nographic", it showed as follows
<img width="529" alt="image" src="https://user-images.githubusercontent.com/60659728/86004973-9b0cb600-ba46-11ea-99dd-5ec8f14bd842.png">
So where is the problem?

**Comment by remzi-arpacidusseau** [comment]
You're best off bugging the MIT folks per xv6 problems. This guide is here to help, but is not definitive... sorry!
