### ISSUE TITLE
Where is "Memory-allocation Library" lab?

### ISSUE THREAD

**Issue by YalandHong** [remzi-arpacidusseau/ostep-projects#20]
Hello,

According to [OSTEP book](http://pages.cs.wisc.edu/~remzi/OSTEP/lab-projects-systems.pdf), there's a lab called "Memory Allocation", which requires students to implement some algorithms for dynamically allocating memory. But the `README` file does not provide its link, and I couldn't find any of its code in this repository.

I don't know whether I missed something or it just does not exist yet.

![image](https://user-images.githubusercontent.com/52960068/101878709-fe406e00-3bca-11eb-8b62-404ae30d8283.png)

**Comment by remzi-arpacidusseau** [comment]
malloc() / free() are in the C standard library and automatically linked
with every C program.
type "man malloc" for more details.

**Comment by YalandHong** [comment]
Hello Professor Arpaci-Dusseau,

I'm sorry but I think you didn't understand what I mean.
I mean, you provide no test case for this lab, nor any code framework.

If you want us to write everything by ourselves, that's ok and I'll close this issue.

**Comment by YalandHong** [comment]
Close due to inactivity
